flags: {}
extra-package-dbs: []
packages:
- '.'

- location:
    git: https://github.com/cspollard/histogram-extras.git
    commit: 294dd30f33a4712681c906408f1643f28c7e023f
  extra-dep: true

- location:
    git: https://github.com/cspollard/variation.git
    commit: 5ec69558ad1e8bc4f94510f851f24671967fc922
  extra-dep: true

- location:
    git: https://github.com/cspollard/hhep.git
    commit: a1169ec9a95f9a199a160d9f122c08bf86a3db66
  extra-dep: true

- location:
    git: https://github.com/cspollard/atlas.git
    commit: 32422e09da45fdd0d4cc59ad855242686df4deae
  extra-dep: true

- location:
    git: https://github.com/cspollard/ttree.git
    commit: 46f342de826a26442545f8da22d8b2fe918751bb
  extra-dep: true

- location:
    git: https://github.com/cspollard/hunfold.git
    commit: d05e0684ba84f1e34bf92e8a38587f44a611cd27
  extra-dep: true

extra-deps:
- cereal-text-0.1.0.2
- histogram-fill-cereal-0.6.2.0
resolver: lts-9.0
