flags:
  text:
    integer-simple: false
extra-package-dbs: []
packages:
- '.'
- ../hhep.git
extra-deps:
- aeson-0.8.1.1
- attoparsec-0.13.0.1
- data-ordlist-0.4.7.0
- dlist-0.7.1.2
- hashable-1.2.3.3
- histogram-fill-0.8.4.1
- histogram-fill-binary-0.6.2.1
- monad-primitive-0.1
- mtl-2.2.1
- primitive-0.6.1.0
- scientific-0.3.4.4
- syb-0.6
- text-1.2.1.3
- unordered-containers-0.2.5.1
- vector-0.11.0.0
resolver: ghc-7.10.3
