flags:
  text:
    integer-simple: false
  aeson:
    old-locale: true
extra-package-dbs: []
packages:
- '.'
extra-deps:
- aeson-0.10.0.0
- attoparsec-0.13.0.1
- dlist-0.7.1.2
- hashable-1.2.3.3
- histogram-fill-0.8.4.1
- monad-primitive-0.1
- mtl-2.2.1
- old-locale-1.0.0.7
- primitive-0.6.1.0
- scientific-0.3.4.4
- syb-0.6
- text-1.2.1.3
- time-1.1.2.4
- unordered-containers-0.2.5.1
- vector-0.10.12.3
resolver: ghc-7.10.3
