flags: {}
extra-package-dbs: []
packages:
- '.'

- location:
    git: https://github.com/cspollard/atlas.git
    commit: master
  extra-dep: true

- location:
    git: https://github.com/cspollard/ttree.git
    commit: master
  extra-dep: true

- location:
    git: https://github.com/cspollard/hunfold.git
    commit: master
  extra-dep: true

- location:
    git: https://github.com/cspollard/histogram-extras.git
    commit: master
  extra-dep: true

- location:
    git: https://github.com/cspollard/variation.git
    commit: master
  extra-dep: true

- location:
    git: https://github.com/cspollard/hhep.git
    commit: master
  extra-dep: true

extra-deps:
- cereal-text-0.1.0.2
- histogram-fill-cereal-0.6.2.0
resolver: lts-8.17
