flags:
  text:
    integer-simple: false
extra-package-dbs: []
packages:
- '.'
- ../hhep.git
extra-deps:
- aeson-0.8.1.1
- async-2.1.0
- attoparsec-0.13.0.1
- blaze-builder-0.4.0.1
- conduit-1.2.6.2
- conduit-extra-1.1.10.1
- data-ordlist-0.4.7.0
- dlist-0.7.1.2
- exceptions-0.8.2.1
- hashable-1.2.4.0
- lifted-base-0.2.3.6
- mmorph-1.0.6
- monad-control-1.0.0.5
- mtl-2.2.1
- network-2.6.2.1
- parallel-3.2.1.0
- primitive-0.6.1.0
- random-1.1
- resourcet-1.1.7.2
- scientific-0.3.4.4
- stm-2.4.4.1
- streaming-commons-0.1.15.1
- syb-0.6
- text-1.2.2.0
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- unordered-containers-0.2.6.0
- vector-0.11.0.0
- zlib-0.6.1.1
resolver: ghc-7.10.3
