flags: {}
extra-package-dbs: []
packages:
- '.'

- location:
    git: https://github.com/cspollard/histogram-extras.git
    commit: 131989aefa7ec40f081e9fbde07c863849e38a4a
  extra-dep: true

- location:
    git: https://github.com/cspollard/variation.git
    commit: 1659fc5412c66b31c0b8f0a36cc75734a9c96454
  extra-dep: true

- location:
    git: https://github.com/cspollard/hhep.git
    commit: 2aae98b10e637f6c52a2b73b6725d7c54cc69942
  extra-dep: true

- location:
    git: https://github.com/cspollard/atlas.git
    commit: 562db6d9aa3e2f8b6023c0d094a7b5c1c9c5da2e
  extra-dep: true

- location:
    git: https://github.com/cspollard/ttree.git
    commit: b6fdf1ddd11758fe611b4b52c2d9e004532ad79c
  extra-dep: true

- location:
    git: https://github.com/cspollard/hunfold.git
    commit: c23d7ededdcedc72c17f0a3051aa6e27c647c63c
  extra-dep: true

extra-deps:
- cereal-text-0.1.0.2
- histogram-fill-cereal-0.6.2.0
resolver: lts-8.17
