flags: {}
extra-package-dbs: []
packages:
- '.'

- location:
    git: https://github.com/cspollard/histogram-extras.git
    commit: 839f490b8969b6d88f72f4ebec0f20fbe1fd9398
  extra-dep: true

- location:
    git: https://github.com/cspollard/variation.git
    commit: 1659fc5412c66b31c0b8f0a36cc75734a9c96454
  extra-dep: true

- location:
    git: https://github.com/cspollard/hhep.git
    commit: 4ebdbd2e7ddc7a7c90303844cd760cf4ee69f966
  extra-dep: true

- location:
    git: https://github.com/cspollard/atlas.git
    commit: f6b0c4f63e1916a193684d4ecc26cb7dcaf51246
  extra-dep: true

- location:
    git: https://github.com/cspollard/ttree.git
    commit: 46f342de826a26442545f8da22d8b2fe918751bb
  extra-dep: true

- location:
    git: https://github.com/cspollard/hunfold.git
    commit: 9e16ce7f124668691f6c3bb0ecc358b77ccf3ed6
  extra-dep: true

extra-deps:
- cereal-text-0.1.0.2
- histogram-fill-cereal-0.6.2.0
resolver: lts-9.0
