flags: {}
extra-package-dbs: []
packages:
- '.'

extra-deps:
  - git: https://github.com/cspollard/histogram-extras.git
    commit: e74e7a17114699c663ba7870e6737159baef7b46

  - git: https://github.com/cspollard/variation.git
    commit: e9874a39eaae7d2675c070ffc9d05e7c97d8a3e3

  - git: https://github.com/cspollard/hhep.git
    commit: 7b413750c82cc6ffd776c603de3e2c42ce8f9cb4

  - git: https://github.com/cspollard/atlas.git
    commit: 633fc6eee0526a8588bbad997e2cbe1759b2c6f9

  - git: https://github.com/cspollard/ttree.git
    commit: a38292370f8c2186379f3b3324583156e47f9694

  - git: https://github.com/cspollard/hunfold.git
    commit: 27efe8785eab0a01ac0382dc97c2140eb15f5fd6

  - histogram-fill-0.9.1.0
  - histogram-fill-cereal-0.8.5.0
  - cereal-text-0.1.0.2

resolver: lts-9.0
