flags: {}
extra-package-dbs: []

packages:
- '.'

extra-deps:    
  - extensible-0.5.1        

  - membership-0        

  - git: https://github.com/cspollard/hunfold.git
    commit: 8ccb29f6bdebfa6f4625d0ee79ea0d95e9583b86

  - git: https://github.com/cspollard/ttree.git
    commit: a38292370f8c2186379f3b3324583156e47f9694

  - git: https://github.com/cspollard/profunctor-hep.git
    commit: 54cede9f0f448bc929467e862d4478b0d33fdd9a

  - git: https://github.com/cspollard/atlas.git
    commit: 5b7e53205dab98243e94281688027393ba6fb72c

  - git: https://github.com/cspollard/hhep.git
    commit: 7b413750c82cc6ffd776c603de3e2c42ce8f9cb4

  - git: https://github.com/cspollard/variation.git
    commit: e9874a39eaae7d2675c070ffc9d05e7c97d8a3e3

  - git: https://github.com/cspollard/histogram-extras.git
    commit: 9d39e8461a723b839c23491a5dedfcc72db136ea

resolver: lts-14.7
