flags: {}
extra-package-dbs: []

packages:
- '.'
- '../hhep.git'
- '../moore.git'
- '../variation.git'
- '../histogram-extras.git'
- '../atlas.git'

extra-deps:    
  - extensible-0.5.1        

  - membership-0        

  - git: https://github.com/cspollard/hunfold.git
    commit: 8ccb29f6bdebfa6f4625d0ee79ea0d95e9583b86

  - git: https://github.com/cspollard/ttree.git
    commit: a38292370f8c2186379f3b3324583156e47f9694

resolver: lts-14.7
